---
label: slurm-local
description: Local SLURM installation for CI
hostname: localhost
transport: core.local
scheduler: core.slurm
shebang: '#!/bin/bash'
work_dir: /tmp/aiida_workdir
mpirun_command: mpirun -np {tot_num_mpiprocs}
mpiprocs_per_machine: 1
prepend_text: ''
append_text: ''
