# Include external CI template from CSCS
# TODO: Possibly 
include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

# Defines the stages for the CI/CD pipeline
# Jobs in earlier stages are run before jobs in later stages.
stages:
  - build
  # - test

# Do we even need a Dockerfile for this? Which OS are the runners
build_job:
  stage: build
  extends: .baremetal-runner-daint-gh200
  variables:
    FIRECREST_CLIENT_SECRET: 'test'
    FIRECREST_CLIENT_ID: 'test'
  script: hostname
    #   - apt-get update -y && apt-get install -y --no-install-recommends graphviz graphviz-dev rabbitmq-server
    # - pip install --upgrade pip
    # - pip install hatch
    # - pip install .
    # - verdi presto --profile-name "ci"
