site_name: MkDocs
site_url: https://github.com/C2SM/WCFlow
site_description: WcFlow a library for creating weather and climate workflows.
site_author:  WcFlow developer team

repo_url: https://github.com/C2SM/WCFlow
docs_dir: src
site_dir: build

markdown_extensions:
  - attr_list

theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  locale: en

nav:
  - Home: index.md
  - Acknowledgements: acknowledgements.md


copyright: Copyright &copy; 2025 by the Sirocco developer team.
