name: test-integration

on:
  push:
    # only pushes to main trigger
    branches: [main]
  pull_request:
    # always triggered

jobs:
  integration_test:
    runs-on: ubuntu-latest
    timeout-minutes: 120 # when icon needs to be rebuild it can take 70 minutes
    strategy:
      matrix:
        python-version: ['3.12']  # ['3.10', '3.11', '3.12', '3.13']
        aiida-version: ['stable']

    permissions:
      packages: write

    services:
      slurm:
        image: xenonmiddleware/slurm:17
        ports:
        - 5001:22

    steps:
    - name: Check access to GitHub secrets
      run: echo "Pull request that trigger this workflow need to be on upstream repo to access GitHub secrets."; exit 1
      # if a pull request is merged from a fork
      if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork

    - uses: actions/checkout@v4

    - name: Set up Spack
      uses: spack/setup-spack@v2
      with:
        buildcache: true

    - name: Install Python and ICON
      env:
        SPACK_OCI_USER: leclairm
        SPACK_OCI_TOKEN: ${{ secrets.SPACK_OCI_TOKEN }}
      run: |
        sudo apt install gcc-11 g++-11 gfortran-11 graphviz graphviz-dev
        spack -e . add python@${{matrix.python-version}}
        spack -e . install

    - name: Push installation to buildcache and update index
      env:
        SPACK_OCI_USER: leclairm
        SPACK_OCI_TOKEN: ${{ secrets.SPACK_OCI_TOKEN }}
      run: spack -e . buildcache push --base-image ubuntu:latest --update-index local-buildcache
      if: ${{ !cancelled() }}

    - name: Install hatch
      shell: spack-bash {0}
      run: |
        spack env activate .
        pip install --upgrade pip
        pip install hatch
        hatch run verdi presto

    - name: Create SSH keys
      shell: spack-bash {0}
      run: |
        spack env activate .
        ssh-keygen -t ed25519 -N "" -f ~/.ssh/upterm_key

        ssh-keygen -q -t rsa -b 4096 -N "" -f "${HOME}/.ssh/id_rsa"
        ssh-keygen -y -f "${HOME}/.ssh/id_rsa" >> "${HOME}/.ssh/authorized_keys"
        ssh-keyscan -H localhost >> "${HOME}/.ssh/known_hosts"

        # The permissions on the GitHub runner are 777 which will cause SSH to refuse the keys and cause authentication to fail
        chmod 755 "${HOME}"

        # Replace the placeholders in configuration files with actual values
        CONFIG="${GITHUB_WORKSPACE}/.github/config"
        cp "${CONFIG}/slurm_rsa" "${HOME}/.ssh/slurm_rsa"
        sed -i "s|PLACEHOLDER_WORK_DIR|${GITHUB_WORKSPACE}|" "${CONFIG}/localhost.yaml"
        sed -i "s|PLACEHOLDER_REMOTE_ABS_PATH_DOUBLER|${CONFIG}/doubler.sh|" "${CONFIG}/doubler.yaml"
        sed -i "s|PLACEHOLDER_SSH_KEY|${HOME}/.ssh/slurm_rsa|" "${CONFIG}/slurm-ssh-config.yaml"

    - name: Set up slurm-ssh computer
      shell: spack-bash {0}
      run: |
        spack env activate .

        CONFIG="${GITHUB_WORKSPACE}/.github/config"
        hatch run verdi computer setup --non-interactive --config "${CONFIG}/slurm-ssh.yaml"
        hatch run verdi computer configure core.ssh slurm-ssh --non-interactive --config "${CONFIG}/slurm-ssh-config.yaml" -n  # needs slurm container
        hatch run verdi computer test slurm-ssh --print-traceback

        hatch run verdi config set runner.poll.interval 0
        hatch run verdi config set warnings.development_version False
        hatch run verdi config set warnings.rabbitmq_version False

    - name: Run ICON tests
      shell: spack-bash {0}
      env:
        PYTEST_ADDOPTS: "--durations=0"
      run: |
        spack env activate .
        hatch test --parallel -- -m "requires_icon" -s tests

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      if: failure()
